### ISSUE TITLE
Permission denied for cache folder

### ISSUE THREAD

**Issue by deulizealand** [thangchung/go-coffeeshop#10]
Hi, i got an error when using dev container to open the project.

did i missing step or something ?

![image](https://user-images.githubusercontent.com/15981200/204951664-2e09c115-7498-4639-9e86-bfa5f24f39cd.png)

**Comment by deulizealand** [comment]
what i do : 
- create folder manually 
- set permission 
- reopen with dev container
This solve the issue

**Comment by thangchung** [comment]
I think the main reason is https://github.com/thangchung/go-coffeeshop/blob/main/.devcontainer/devcontainer.json#L14
It runs as `vscode` user, but the code actually needs `root` to resolve pkg, at the moment, we can `sudo su` into `root` user, then run `go mod tidy`, then it works normally.

I will fix this issue soon. Thanks for the finding

**Comment by deulizealand** [comment]
Thanks for the Feedback.

**Comment by thangchung** [comment]
Fixed in the latest version in the main branch at https://github.com/thangchung/go-coffeeshop/commit/22d33190a0cf81630878e47bafae2de7c0abb783. Feel free to re-open it if there are still things else to fix.
