### ISSUE TITLE
level=info msg="Queue bound to exchange, starting to consume from queue, consumerTag: counter-order-consumer"

### ISSUE THREAD

**Issue by arpitcoder** [thangchung/go-coffeeshop#12]
At the step where the go-coffee-counter container starts it freezes with no result please help.

**Comment by 53jk1** [comment]
This message indicates that a queue has been successfully bound to an exchange, and that a consumer with the specified tag is now consuming messages from the queue. This is a common message when setting up messaging systems with queues and exchanges. Try check the configuration of the container, or any other services that it needs to communicate with.

**Comment by thangchung** [comment]
Fixed in the latest version in the main branch at https://github.com/thangchung/go-coffeeshop/commit/22d33190a0cf81630878e47bafae2de7c0abb783. Feel free to re-open it if there are still things else to fix.
