### ISSUE TITLE
How to run demo in local PC?

### ISSUE THREAD

**Issue by TomJarray** [thangchung/go-coffeeshop#18]
I would like to run this project on local mac book, but don't know how to run it? which softwares I need to install?
Do you have any detailed installation guide?

**Comment by viper-00** [comment]
I think you can install Docker on your mac, then use following command:

```
> docker-compose -f docker-compose-full.yaml build
> docker-compose -f docker-compose-full.yaml up
```

**Comment by TomJarray** [comment]
It can work well after installing Docker, thank you very much!

**Comment by niceguyblue** [comment]
Getting
go-coffeeshop-postgres-1: FATAL:  role "root" does not exist
