### ISSUE TITLE
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-full.yaml'

### ISSUE THREAD

**Issue by huynhtruc0309** [thangchung/go-coffeeshop#23]
I jumped into .devcontainer, then ran

`> docker-compose -f docker-compose-full.yaml build`

I got this error 

`ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-full.yaml'`

I tried to `cd ..`
and run above command again then got

```
ERROR: The Compose file './docker-compose-full.yaml' is invalid because:
services.barista.depends_on contains an invalid type, it should be an array
services.counter.depends_on contains an invalid type, it should be an array
services.kitchen.depends_on contains an invalid type, it should be an array
```

What did it go wrong?
Thank you.

**Comment by thangchung** [comment]
Fixed in the latest version in the main branch at https://github.com/thangchung/go-coffeeshop/commit/22d33190a0cf81630878e47bafae2de7c0abb783. Feel free to re-open it if there are still things else to fix.

**Comment by huynhtruc0309** [comment]
Hi @thangchung 
I got `make: *** No rule to make target `docker-compose'.  Stop.` after running `make docker-compose`. 
How to fix it? Thank you very much
