### ISSUE TITLE
Infrastructure Nomad

### ISSUE THREAD

**Issue by phantoms158** [thangchung/go-coffeeshop#29]
Hi anh thangchung, 

Anh cho em hỏi là với source code nomad hiện tại thì có thể chạy trên production được không anh, hay khi chạy trên production còn cần config gì nữa ạ, em đang học nomad nên chưa rõ lắm.

anh có thể cho e xin tài liệu hoặc tutorial gì đó để học nomad được không ạ vì trên document của hashicorp khá là rời rạc em không thể hiểu rõ nomad và consul được ạ em cám ơn anh

**Comment by thangchung** [comment]
Chạy thì được em nhé, nhưng khi e setup con Nomad cho production thì e phải quan tâm cơ chế clustering con Nomad và Consult nữa mới tự tin chạy production được nhé. A đóng issue, có gì nếu cần thảo luận thêm thì e có thể mở issue lại nhé
